-- changeset sfishkov:1
create table items
(
    id          bigint generated by default as identity,
    description varchar(1000),
    img_path    varchar(255),
    price       bigint       not null check (price >= 0),
    title       varchar(255) not null,
    primary key (id)
);

-- changeset sfishkov:2
create table cart_items
(
    id       bigint generated by default as identity,
    item_id  bigint       not null,
    count    integer      not null check (count >= 0),
    primary key (id)
);

-- changeset sfishkov:3
create table orders
(
    id bigint generated by default as identity,
    primary key (id)
);

-- changeset sfishkov:4
create table order_items
(
    id       bigint generated by default as identity,
    order_id bigint       not null,
    item_id  bigint       not null,
    count    integer      not null,
    price    bigint       not null,
    title    varchar(255) not null,
    primary key (id)
);

-- changeset sfishkov:5
alter table if exists cart_items
    add constraint fk_cart_items_item_id_items_id
        foreign key (item_id)
            references items ON DELETE CASCADE;

-- changeset sfishkov:6
alter table if exists order_items
    add constraint fk_order_items_order_id_orders_id
        foreign key (order_id)
            references orders ON DELETE CASCADE;

-- changeset sfishkov:7
alter table if exists order_items
    add constraint uq_order_items_order_id_item_id
        unique (order_id, item_id);