-- changeset sfishkov:1
create table users
(
    id          bigint generated by default as identity,
    login       varchar(255) not null,
    password    varchar(255) not null,
    name        varchar(255) not null,
    primary key (id)
);

-- changeset sfishkov:2
alter table if exists users
    add constraint uq_users_login
        unique (login);

-- changeset sfishkov:3
alter table if exists cart_items
    add column user_id bigint not null;
alter table if exists cart_items
    add constraint fk_cart_items_user_id_users_id
        foreign key (user_id) references users(id);

-- changeset sfishkov:4
alter table if exists orders
    add column user_id bigint not null;
alter table if exists orders
    add constraint fk_orders_user_id_users_id
        foreign key (user_id) references users(id);