openapi: 3.1.0
info:
  title: Payment Api
  description: Payment Api for My market application
  version: 1.0.0

tags:
  - name: Balance
  - name: Payment

servers:
  - url: http://localhost:{port}
    description: Local development server
    variables:
      port:
        default: '8081'

paths:
  /balance:
    get:
      summary: Get balance
      operationId: getBalance
      tags:
        - Balance
      responses:
        200:
          description: Balance retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
      security:
        - bearerAuth: [payment-balance-read]

  /payments:
    post:
      summary: Make payment
      operationId: makePayment
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
      responses:
        200:
          description: Payment successful
        400:
          description: Bad request
        422:
          description: Insufficient balance
      security:
        - bearerAuth: [payment-balance-write]

components:
  securitySchemes:
    bearerAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://localhost:9090/realms/mma/protocol/openid-connect/token
          scopes:
            payment-balance-read: read balance
            payment-balance-write: write payments

  schemas:
    BalanceResponse:
      type: object
      required:
        - balance
      properties:
        balance:
          type: integer
          format: int64
      example:
        balance: 10000

    PaymentRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: integer
          format: int64
          minimum: 1
      example:
        amount: 990